### ISSUE TITLE
Iris Door/Window Device Handler

### ISSUE THREAD

**Issue by jfrux** [mitchpond/SmartThingsPublic#16]
Do you know if this device handler polls for the temp and stuff?
I just got mine about 2.5 weeks ago and the batteries are already at 66%.

Now, granted, they are installed in a garage where the temperature can fluctuate quite a bit... is there any way to slow the battery drain at all?

Just curious!

Oh, and thank you for all you do for the community!  You rock!

**Comment by mitchpond** [comment]
There is no polling done by the handler. All reports are pushed by the
device, unless a refresh is sent manually. ZigBee devices don't report
their battery level in a precise enough manner to get anything more than
0.1 volt steps. So 66% can be anywhere from 66 to 87%. Being in northern
Wisconsin, I've seen battery levels on some of mine dip, but then recover
when they warm up from the sun.

Also, the batteries I've gotten with a few devices were fairly weak out of
the box. I'll bet that it stays at 66% for a while though.

**Comment by jfrux** [comment]
That's reassuring.

Thanks Mitch!
:)
